projects = { 'C:\\Users\\hr-hm\\Desktop\\manaby-todos' = { trust_level = "trusted" } , 'C:\\Users\\hr-hm\\Desktop\\codex' = { trust_level = "trusted" } }
model_reasoning_effort = "high"
hide_agent_reasoning = true
show_raw_agent_reasoning = false




approval_policy = "never"

# MCPサーバーの定義（これは一例です）


# Serena MCP サーバー設定
[mcp_servers.serena]
command = "uvx"
# Windows パスはバックスラッシュを二重にエスケープする
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex-ja", "--project", "C:\\Users\\hr-hm\\Desktop\\codex"]