import { SoundDefinition, SoundId } from "./types";

export const SFX_BASE_PATH = "/sfx";

export const AUDIO_EXTENSIONS = ["webm", "ogg", "mp3", "wav"] as const;

const createDefinition = (definition: SoundDefinition) => definition;

export const SOUND_LIBRARY: SoundDefinition[] = [
  createDefinition({
    id: "ui_click",
    category: "ui",
    preload: { link: false, decode: false },
    variants: [],
    note: "Disabled placeholder (no actual asset)",
  }),
  createDefinition({
    id: "card_flip",
    category: "card",
    preload: { link: true, decode: true },
    variants: [{ src: "card/card_flip.ogg" }],
    playbackRateRange: { min: 0.92, max: 1.03 },
    gainDbRange: { min: -6, max: -3.5 },
    startOffsetMsRange: { min: 0, max: 20 },
    note: "Card reveal or flip",
  }),
  createDefinition({
    id: "card_place",
    category: "card",
    preload: { link: true, decode: true },
    variants: [{ src: "card/card_place.ogg" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -5, max: -3 },
    note: "Place card into slot",
  }),
  createDefinition({
    id: "card_deal",
    category: "card",
    preload: { link: true, decode: true },
    variants: [{ src: "card/card_deal.ogg" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -6, max: -3.5 },
    note: "Deal cards to players",
  }),
  createDefinition({
    id: "topic_shuffle",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/topic_shuffle.ogg" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -6, max: -3.5 },
    note: "Shuffle topic selection",
  }),
  createDefinition({
    id: "reset_game",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/reset_game.ogg" }],
    playbackRateRange: { min: 0.9, max: 1.05 },
    gainDbRange: { min: -6, max: -4 },
    note: "Game reset action",
    stopPrevious: true,
  }),
  createDefinition({
    id: "clear_success1",
    category: "fanfare",
    preload: { link: true, decode: true },
    variants: [{ src: "result/clear_success1.mp3" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -2, max: 0 },
    note: "Success celebration (normal)",
    stopPrevious: true,
    duck: { amount: 0.15, releaseMs: 6000 },
  }),
  createDefinition({
    id: "clear_success2",
    category: "fanfare",
    preload: { link: true, decode: true },
    variants: [{ src: "result/clear_success2.mp3", gainMultiplier: 0.5 }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -2, max: 0 },
    note: "Success celebration (epic)",
    stopPrevious: true,
    duck: { amount: 0.15, releaseMs: 6000 },
  }),
  createDefinition({
    id: "clear_failure",
    category: "fanfare",
    preload: { link: true, decode: true },
    variants: [{ src: "result/clear_failure.ogg" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -2.5, max: -0.5 },
    note: "Failure animation sting",
    stopPrevious: true,
    duck: { amount: 0.25, releaseMs: 1500 },
  }),
  createDefinition({
    id: "drop_success",
    category: "drag",
    preload: { link: true, decode: true },
    variants: [{ src: "card/card_place.ogg" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -5, max: -2.5 },
    note: "Valid drop interaction",
  }),
  createDefinition({
    id: "notify_success",
    category: "notify",
    preload: { link: false, decode: false },
    variants: [],
    note: "Disabled placeholder (no actual asset)",
  }),
  createDefinition({
    id: "notify_error",
    category: "notify",
    preload: { link: false, decode: false },
    variants: [],
    note: "Disabled placeholder (no actual asset)",
  }),
  createDefinition({
    id: "notify_warning",
    category: "notify",
    preload: { link: false, decode: false },
    variants: [],
    note: "Disabled placeholder (no actual asset)",
  }),
  createDefinition({
    id: "result_victory",
    category: "fanfare",
    preload: { link: false, decode: false },
    variants: [],
    note: "Disabled placeholder (no actual asset)",
  }),
  createDefinition({
    id: "result_failure",
    category: "fanfare",
    preload: { link: false, decode: false },
    variants: [],
    note: "Disabled placeholder (no actual asset)",
  }),
  createDefinition({
    id: "round_start",
    category: "fanfare",
    preload: { link: true, decode: true },
    variants: [{ src: "system/round_start.ogg" }],
    playbackRateRange: { min: 0.99, max: 1.01 },
    gainDbRange: { min: -4, max: -2 },
    note: "Round intro fanfare",
    stopPrevious: true,
    duck: { amount: 0.22, releaseMs: 2600 },
  }),
  createDefinition({
    id: "clue_decide",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/clue_decide.ogg" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5.5, max: -3.5 },
    note: "Confirm clue entry",
  }),
  createDefinition({
    id: "ledger_open",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/ledger_open.ogg" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5, max: -3 },
    note: "Open party records modal",
  }),
  createDefinition({
    id: "ledger_close",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/ledger_close.ogg" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5, max: -3 },
    note: "Close party records modal",
  }),
  createDefinition({
    id: "settings_open",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/settings_open.ogg" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5.5, max: -3.5 },
    note: "Open settings modal",
  }),
  createDefinition({
    id: "settings_close",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/settings_close.ogg" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5.5, max: -3.5 },
    note: "Close settings modal",
  }),
  createDefinition({
    id: "bgm1",
    category: "ambient",
    preload: { link: true, decode: true },
    variants: [{ src: "ambient/bgm1.mp3" }],
    loop: true,
    stopPrevious: true,
    gainDbRange: { min: -4, max: -2 },
    note: "Primary background music",
  }),
  createDefinition({
    id: "order_confirm",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/order_confirm.ogg" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5, max: -3 },
    note: "Confirm ordering",
  }),
];

export const SOUND_INDEX: Record<SoundId, SoundDefinition> = SOUND_LIBRARY.reduce(
  (acc, definition) => {
    acc[definition.id] = definition;
    return acc;
  },
  {} as Record<SoundId, SoundDefinition>
);
