import { SoundDefinition, SoundId } from "./types";

export const SFX_BASE_PATH = "/sfx";

export const AUDIO_EXTENSIONS = ["webm", "ogg", "mp3", "wav"] as const;

const createDefinition = (definition: SoundDefinition) => definition;

export const SOUND_LIBRARY: SoundDefinition[] = [
  createDefinition({
    id: "ui_click",
    category: "ui",
    preload: { link: true, decode: true },
    variants: [{ src: "ui/ui_click" }],
    playbackRateRange: { min: 0.96, max: 1.04 },
    gainDbRange: { min: -5, max: -3 },
    startOffsetMsRange: { min: 0, max: 12 },
    note: "Primary button interactions",
  }),
  createDefinition({
    id: "card_flip",
    category: "card",
    preload: { link: true, decode: true },
    variants: [{ src: "card/card_flip" }],
    playbackRateRange: { min: 0.92, max: 1.03 },
    gainDbRange: { min: -6, max: -3.5 },
    startOffsetMsRange: { min: 0, max: 20 },
    note: "Card reveal or flip",
  }),
  createDefinition({
    id: "card_place",
    category: "card",
    preload: { link: true, decode: true },
    variants: [{ src: "card/card_place" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -5, max: -3 },
    note: "Place card into slot",
  }),
  createDefinition({
    id: "card_deal",
    category: "card",
    preload: { link: true, decode: true },
    variants: [{ src: "card/card_deal" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -6, max: -3.5 },
    note: "Deal cards to players",
  }),
  createDefinition({
    id: "topic_shuffle",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/topic_shuffle" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -6, max: -3.5 },
    note: "Shuffle topic selection",
  }),
  createDefinition({
    id: "reset_game",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/reset_game" }],
    playbackRateRange: { min: 0.9, max: 1.05 },
    gainDbRange: { min: -6, max: -4 },
    note: "Game reset action",
    stopPrevious: true,
  }),
  createDefinition({
    id: "clear_success1",
    category: "fanfare",
    preload: { link: true, decode: true },
    variants: [{ src: "result/clear_success1.mp3" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -2, max: 0 },
    note: "Success celebration (normal)",
    stopPrevious: true,
  }),
  createDefinition({
    id: "clear_success2",
    category: "fanfare",
    preload: { link: true, decode: true },
    variants: [{ src: "result/clear_success2.mp3", gainMultiplier: 0.5 }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -2, max: 0 },
    note: "Success celebration (epic)",
    stopPrevious: true,
  }),
  createDefinition({
    id: "clear_failure",
    category: "fanfare",
    preload: { link: true, decode: true },
    variants: [{ src: "result/clear_failure" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -2.5, max: -0.5 },
    note: "Failure animation sting",
    stopPrevious: true,
  }),
  createDefinition({
    id: "drag_pickup",
    category: "drag",
    preload: { link: true, decode: true },
    variants: [{ src: "dnd/drag_pickup" }],
    playbackRateRange: { min: 0.94, max: 1.02 },
    gainDbRange: { min: -5, max: -3 },
    note: "User starts dragging a card",
  }),
  createDefinition({
    id: "drop_success",
    category: "drag",
    preload: { link: true, decode: true },
    variants: [{ src: "dnd/drop_success" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -5, max: -2.5 },
    note: "Valid drop interaction",
  }),
  createDefinition({
    id: "drop_invalid",
    category: "drag",
    preload: { link: true, decode: true },
    variants: [{ src: "dnd/drop_invalid" }],
    playbackRateRange: { min: 0.95, max: 1.05 },
    gainDbRange: { min: -6.5, max: -4 },
    note: "Invalid drop feedback",
    stopPrevious: true,
  }),
  createDefinition({
    id: "notify_success",
    category: "notify",
    preload: { link: true, decode: true },
    variants: [{ src: "notify/notify_success" }],
    playbackRateRange: { min: 0.97, max: 1.02 },
    gainDbRange: { min: -5, max: -3 },
    note: "Toast success",
  }),
  createDefinition({
    id: "notify_error",
    category: "notify",
    preload: { link: true, decode: true },
    variants: [{ src: "notify/notify_error" }],
    playbackRateRange: { min: 0.9, max: 1.02 },
    gainDbRange: { min: -5, max: -3 },
    note: "Toast failure",
    stopPrevious: true,
  }),
  createDefinition({
    id: "result_victory",
    category: "fanfare",
    variants: [{ src: "result/result_victory" }],
    playbackRateRange: { min: 0.98, max: 1.02 },
    gainDbRange: { min: -0.5, max: 1.5 },
    minDelaySeconds: 0.05,
    note: "Short win jingle",
  }),
  createDefinition({
    id: "result_failure",
    category: "fanfare",
    variants: [{ src: "result/result_failure" }],
    playbackRateRange: { min: 0.95, max: 1.02 },
    gainDbRange: { min: -0.5, max: 0.5 },
    minDelaySeconds: 0.05,
    note: "Short fail sting",
  }),
  createDefinition({
    id: "notify_warning",
    category: "notify",
    preload: { link: true, decode: true },
    variants: [{ src: "notify/notify_warning" }],
    playbackRateRange: { min: 0.96, max: 1.04 },
    gainDbRange: { min: -5, max: -3 },
    note: "Toast warning",
  }),
  createDefinition({
    id: "round_start",
    category: "fanfare",
    preload: { link: true, decode: true },
    variants: [{ src: "system/round_start" }],
    playbackRateRange: { min: 0.99, max: 1.01 },
    gainDbRange: { min: -4, max: -2 },
    note: "Round intro fanfare",
    stopPrevious: true,
  }),
  createDefinition({
    id: "clue_decide",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/clue_decide" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5.5, max: -3.5 },
    note: "Confirm clue entry",
  }),
  createDefinition({
    id: "ledger_open",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/ledger_open" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5, max: -3 },
    note: "Open party records modal",
  }),
  createDefinition({
    id: "ledger_close",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/ledger_close" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5, max: -3 },
    note: "Close party records modal",
  }),
  createDefinition({
    id: "settings_open",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/settings_open" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5.5, max: -3.5 },
    note: "Open settings modal",
  }),
  createDefinition({
    id: "settings_close",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/settings_close" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5.5, max: -3.5 },
    note: "Close settings modal",
  }),
  createDefinition({
    id: "bgm1",
    category: "ambient",
    variants: [{ src: "ambient/bgm1.mp3" }],
    loop: true,
    stopPrevious: true,
    gainDbRange: { min: -4, max: -2 },
    note: "Primary background music",
  }),
  createDefinition({
    id: "order_confirm",
    category: "system",
    preload: { link: true, decode: true },
    variants: [{ src: "system/order_confirm" }],
    playbackRateRange: { min: 0.97, max: 1.03 },
    gainDbRange: { min: -5, max: -3 },
    note: "Confirm ordering",
  }),
];

export const SOUND_INDEX: Record<SoundId, SoundDefinition> = SOUND_LIBRARY.reduce(
  (acc, definition) => {
    acc[definition.id] = definition;
    return acc;
  },
  {} as Record<SoundId, SoundDefinition>
);
