export { BoardFrame } from "./BoardFrame";
export { InteractiveBoard } from "./InteractiveBoard";
export { StaticBoard } from "./StaticBoard";
export { usePlayerPresenceState } from "./usePlayerPresenceState";
export { useRevealStatus } from "./useRevealStatus";
export { useResultFlipState } from "./useResultFlipState";
export { useDragMagnetController } from "./useDragMagnetController";
export { RETURN_DROP_ZONE_ID, createInitialMagnetState, MAGNET_IDLE_MARGIN_PX } from "./constants";
export { boardCollisionDetection } from "./boardCollisionDetection";
export { getActiveRectWithDelta, snapshotRect } from "./dragRects";
export type { MagnetSnapshot } from "./types";
