export { BoardFrame } from "./BoardFrame";
export { CentralCardBoardView } from "./CentralCardBoardView";
export { InteractiveBoard } from "./InteractiveBoard";
export { StaticBoard } from "./StaticBoard";
export { usePlayerPresenceState } from "./usePlayerPresenceState";
export { useRevealStatus } from "./useRevealStatus";
export { useResultFlipState } from "./useResultFlipState";
export { useDragMagnetController } from "./useDragMagnetController";
export { RETURN_DROP_ZONE_ID, createInitialMagnetState, MAGNET_IDLE_MARGIN_PX } from "./constants";
export { boardCollisionDetection } from "./boardCollisionDetection";
export { getActiveRectWithDelta, snapshotRect } from "./dragRects";
export type { MagnetSnapshot } from "./types";

export { useBoardA11yMessage } from "./useBoardA11yMessage";
export { useBoardActiveProposal } from "./useBoardActiveProposal";
export { useBoardBoundsTracker } from "./useBoardBoundsTracker";
export { useBoardCardRenderer } from "./useBoardCardRenderer";
export { useBoardClearActive } from "./useBoardClearActive";
export { useBoardDebugDumpBundle } from "./useBoardDebugDumpBundle";
export { useBoardDropAnimation } from "./useBoardDropAnimation";
export { useBoardDropState } from "./useBoardDropState";
export { useBoardDragBoostState } from "./useBoardDragBoostState";
export { useBoardDragCancelHandlers } from "./useBoardDragCancelHandlers";
export { useBoardDragEndHandler } from "./useBoardDragEndHandler";
export { useBoardDragMoveHandler } from "./useBoardDragMoveHandler";
export { useBoardDragSensors } from "./useBoardDragSensors";
export { useBoardDragStartHandler } from "./useBoardDragStartHandler";
export { useBoardMagnetConfig } from "./useBoardMagnetConfig";
export { useBoardOptimisticReturning } from "./useBoardOptimisticReturning";
export { useBoardPlaceholderSlots } from "./useBoardPlaceholderSlots";
export { useBoardPresenceBundle } from "./useBoardPresenceBundle";
export { useBoardRevealState } from "./useBoardRevealState";
export { useBoardRoomKeys } from "./useBoardRoomKeys";
export { useBoardSlotCountState } from "./useBoardSlotCountState";
export { useBoardSlotDescriptors } from "./useBoardSlotDescriptors";
export { useBoardSlotHoverHandlers } from "./useBoardSlotHoverHandlers";
export { usePendingPruneEffects } from "./usePendingPruneEffects";
export { useProposalSyncTrace } from "./useProposalSyncTrace";
export { useRevealDoneFallback } from "./useRevealDoneFallback";
export { useStreakBannerState } from "./useStreakBannerState";
export { useVictoryRaysPrefetch } from "./useVictoryRaysPrefetch";
export { buildCentralCardBoardViewProps } from "./buildCentralCardBoardViewProps";
export { isBoardInteractive } from "./boardUiFlags";
export { useOptimisticProposalState } from "./useOptimisticProposalState";
export { useBoardReleaseMagnet } from "./useBoardReleaseMagnet";
